version: "2.0"
services:
  openlibry:
    container_name: openlibry
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./database:/app/prisma/database
      - ./public/coverimages:/app/public/coverimages
